version: '3'

services:
    server:
        image: ambientum/node:14
        container_name: coodesh_challenge_server
        restart: 'always'
        command: bash -c "npm i && npm run dev"
        ports:
            - '${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}'
            - '8001:8001'
        network_mode: 'host'
        volumes:
            - .:/var/www/app
    database:
        image: postgres:10.5
        container_name: coodesh_challenge_database
        restart: 'always'
        environment:
          - POSTGRES_USER=DATABASE_USER
          - POSTGRES_PASSWORD=DATABASE_PASSWORD
        ports:
          - '5438:5432'
        network_mode: 'host'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
