version: '3'

services:
    server:
        image: ambientum/node:14
        container_name: coodesh_challenge_server
        restart: 'always'
        command: bash -c "npm i && npm run dev"
        network_mode: 'host'
        volumes:
            - .:/var/www/app
    database:
        image: postgres
        container_name: coodesh_challenge_database
        restart: 'always'
        environment:
          - POSTGRES_USER=${DATABASE_USER}
          - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        network_mode: 'host'
        volumes: 
          - ./database:/var/lib/postgresql/data
